# Server Configuration
server:
  port: 1991
  address: 0.0.0.0
  error:
    include-stacktrace: always
  compression:
    enabled: true

# Datasource Configuration for SQL Server
spring:
  application:
    name: spring-boot-3
  main:
    allow-bean-definition-overriding: true
  # Jackson Configuration
  jackson:
    date-format: yyyy-MM-dd
  datasource:
#    url: jdbc:sqlserver://<IP>:<PORT>;databaseName=<NAME>;trustServerCertificate=true;
#    username: <USERNAME>
#    password: <PASSWORD>
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:mysql://localhost:3306/gems?trustServerCertificate=true;
    username: nazran
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Hikari Configuration
    hikari:
      minimum-idle: 1
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

  # JPA Configuration
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.SQLServer2012Dialect
        dialect: org.hibernate.dialect.MySQLDialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        format_sql: true
        use_sql: true
        shutdown_on_session_factory_close: false
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
          legacy_limit_handler: true

    # Hibernate Configuration
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # for swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # Servlet Configuration
  servlet:
    multipart:
      enabled: true
      location: /tmp
      max-file-size: 500KB
      max-request-size: 500KB
      resolve-lazily: false
